-- ============================================================================
-- 타오운세 2.0 — 0006 fortune content pools (free readings source content)
-- Ported from 1.0. Standalone (no FKs). RLS public-read.
-- lotto.id: GENERATED ALWAYS → BY DEFAULT (so id values can be copied verbatim).
-- today: kept PK-less to mirror 1.0 exactly.
-- ============================================================================

-- 띠별 오늘의 운세 (daily)
create table if not exists public.daily_horoscope (
  id          uuid default gen_random_uuid() primary key,
  target_date date not null,
  zodiac_ko   varchar(10) not null,
  birth_years text not null,
  "content"   text not null,
  created_at  timestamptz default now(),
  lang        varchar(5) default 'ko' not null,
  constraint daily_horoscope_unique unique (target_date, zodiac_ko, lang)
);
create index if not exists idx_horoscope_date on public.daily_horoscope using btree (target_date);

-- 오늘의 운세 content pool (no PK in 1.0 — mirrored)
create table if not exists public.today (
  id         int8 not null,
  total      text,
  "money"    text,
  biz        text,
  job        text,
  love       text,
  wish       text,
  hope       text,
  "number"   varchar,
  created_at timestamptz not null,
  nation     varchar default 'k'
);

-- 데이트 운세 content pool
create table if not exists public.today_date_unse (
  id         int8 generated by default as identity primary key,
  num        varchar,
  sex        varchar,
  datetotal  text,
  dateplace  text,
  datewish   text,
  created_at timestamptz default now() not null,
  nation     varchar default 'k' not null
);

-- 이달의 운세 content pool
create table if not exists public.month_unse (
  id        int8 generated by default as identity primary key,
  num       varchar,
  total     text,
  manwoman  text,
  date_unse text,
  kind_unse text,
  created_at timestamptz default now() not null,
  nation    varchar default 'k'
);

-- 토정비결 content pool (월별 jan..dec)
create table if not exists public.tojung (
  id    int8 generated by default as identity primary key,
  num   varchar,
  total text,
  jan text, feb text, mar text, apr text, may text, jun text,
  jul text, aug text, sep text, oct text, nov text, "dec" text,
  created_at timestamptz default now() not null,
  nation varchar default 'k'
);

-- 평생운세 content pool
create table if not exists public.lifeall (
  id         int8 generated by default as identity primary key,
  num        varchar,
  sajuwoon   text,
  earlyyear  text,
  middleyear text,
  lastyear   text,
  lovewealth text,
  jobhealth  text,
  created_at timestamptz default now() not null,
  nation     varchar(10) default 'k'
);

-- 로또 운세 content pool
create table if not exists public.lotto (
  id         int4 generated by default as identity primary key,
  num        varchar not null,
  unsetotal  text,
  lottolucky text,
  wish       text,
  created_at timestamptz not null,
  nation     varchar(10) default 'k'
);

-- RLS: public read on all content pools
do $$
declare t text;
begin
  foreach t in array array['daily_horoscope','today','today_date_unse','month_unse','tojung','lifeall','lotto']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t||'_select_public', t);
    execute format('create policy %I on public.%I for select using (true)', t||'_select_public', t);
  end loop;
end $$;
