-- ============================================================================
-- 타오운세 2.0 — 0007 customer inquiries (문의하기 submissions)
-- Guests submit via the server API using the service role; RLS is enabled with
-- NO public policies, so the anon/client key can neither read nor write this
-- table directly (inquiries contain PII: name + email). Modeled on 1.0's
-- public.customer_inquiries, plus a `type` column for the form's 문의 유형.
-- ============================================================================
create table if not exists public.customer_inquiries (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null,
  email      varchar(255) not null,
  type       varchar(30),
  subject    varchar(255) not null,
  content    text not null,
  status     varchar(20) default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_customer_inquiries_created on public.customer_inquiries (created_at desc);

-- RLS on, no policies → service_role only (server-side inserts).
alter table public.customer_inquiries enable row level security;
