-- 로또 운세 개편: 주간 7일 day-phrase 풀(lotto_daily).
-- 기존 lotto 테이블(운세총론=unsetotal / 구입전략=lottolucky / 희망=wish, 192행)은 무변경.
-- 번호/표/속성/게이지는 명식 엔진에서 계산하므로 텍스트 풀이 필요 없고,
-- 주간 7일 각 날짜의 한 줄 멘트만 강도(bucket 0~4)별로 풀에서 고른다.

create table if not exists public.lotto_daily (
  id         int4 generated by default as identity primary key,
  bucket     int2 not null,                       -- 0(매우 약) ~ 4(매우 강)
  nation     varchar(10) not null default 'k',    -- k/e/j/c
  phrase     text not null,
  created_at timestamptz not null default now(),
  constraint lotto_daily_unique unique (bucket, nation)
);

-- RLS: public read (0006_fortune_content.sql 패턴)
alter table public.lotto_daily enable row level security;
drop policy if exists lotto_daily_select_public on public.lotto_daily;
create policy lotto_daily_select_public on public.lotto_daily for select using (true);

-- 시딩: 5 bucket × 4 nation = 20행.
insert into public.lotto_daily (bucket, nation, phrase) values
  -- 한국어(k)
  (0, 'k', '구입을 자제하는 것이 좋은 날입니다. 재물의 흐름에 막힘이 많습니다.'),
  (1, 'k', '큰 기대는 잠시 접어두세요. 당첨운이 다소 약한 날입니다.'),
  (2, 'k', '평범한 흐름의 날입니다. 무리한 베팅보다 소액이 어울립니다.'),
  (3, 'k', '재정적인 감이 좋은 날입니다. 가벼운 도전을 노려볼 만합니다.'),
  (4, 'k', '행운도가 높은 날입니다. 평소보다 조금 과감히 노려봐도 좋습니다.'),
  -- 영어(e)
  (0, 'e', 'Hold off today — wealth energy is blocked and luck runs low.'),
  (1, 'e', 'Keep expectations modest; winning luck is weak today.'),
  (2, 'e', 'An ordinary day. A small ticket suits you better than a big bet.'),
  (3, 'e', 'Your financial instincts are sharp — a light try is worthwhile.'),
  (4, 'e', 'Luck runs high today. You may aim a little bolder than usual.'),
  -- 일본어(j)
  (0, 'j', '本日は購入を控えめに。金運の流れが滞りがちです。'),
  (1, 'j', '大きな期待は禁物。当選運がやや弱い一日です。'),
  (2, 'j', '平凡な流れの日。大勝負より少額が似合います。'),
  (3, 'j', '金銭感覚が冴える日。軽い挑戦なら狙う価値があります。'),
  (4, 'j', '幸運度の高い一日。いつもより少し大胆に狙ってもよいでしょう。'),
  -- 중국어(번체, 대만 c)
  (0, 'c', '今日宜暫緩購買，財氣流動較為阻滯。'),
  (1, 'c', '別抱太大期待，今日中獎運偏弱。'),
  (2, 'c', '平穩的一天，小額比重注更適合你。'),
  (3, 'c', '財務直覺敏銳的一天，輕鬆一試值得。'),
  (4, 'c', '今日運勢高漲，可比平時更大膽出手。')
on conflict (bucket, nation) do nothing;
